### PR TITLE
LCTRL 8/SCTRL 8

### LINKED ISSUE #51: LCTRL 8 / SCTRL 8 - get/set ASM pointer
With the JIT plugin, doing this:

```pawn
#emit LOAD.S.pri pointer
#emit SCTRL      6
```

For a dynamic jump is quite inefficient - actually less so than in the VM because of the address translations required.  This is unfortunate but understandable.  I'm proposing `LCTRL 8` to load the compiled address of the AMX address in `pri` in to `pri`, and `SCTRL 8` to jump straight to that exact assembly location in the JIT.  I realise there are serious uses of abuse with this, but with all the other ways of executing arbitrary ASM and the damage caused by an invalid `SCTRL 6`, I think this problem is minor.  The above code would thus be equivalent to:

```pawn
#emit LOAD.S.pri pointer
#emit LCTRL      8
#emit SCTRL      8
```

Or a loop of this:

```pawn
{
	#emit LOAD.S.pri pointer
	#emit SCTRL      6
}
```

Could become this:

```pawn
#emit LOAD.S.pri pointer
#emit LCTRL      8
#emit STOR.S.pri pointer
{
	#emit LOAD.S.pri pointer
	#emit SCTRL      8
}
```

Thus doing the lookup only once.  The real address could also be stored by libraries like y_inline (which I'm trying to get JIT compatible) when it detects that the JIT is in use.  `LCTRL 7` is helpfuly a NO-OP when the JIT plugin isn't there.  These would probably be so as well - the `LCTRL 8` would work quite nicely as the contents of `pri` wouldn't get modified at all.  But `SCTRL 8` would not jump instead of jumping, and that's bad, so they could not be used execpt when runtime detection proves that the JIT exists.

### PR DESCRIPTION
**Pull request by Y-Less**
Closes #51

### CODE REVIEW

**Comment by Y-Less** [comment]
I originally made a pull request with just a few commits, while working on some other stuff.  I forgot that they would be appended to this pull request.

**Comment by Y-Less** [comment]
Also now closes #52

**Comment by Y-Less** [comment]
I reverted all the changes I hadn't originally intended to include in this pull request.  They were mostly meant to be tests, not pushed upstream yet (or potentially ever).  I'm still not sold on them, there are potentially better ways of detecting if the JIT is present, though I don't know of another way of detecting `SCTRL 8` inside OnJITCompile without those other changes.  In YSI I will probably hook `OnJITCompile` and save the fact that it exists, but I don't know of a way to use `LCTRL 8` reliably as I said.

**Comment by Zeex** [comment]
Nice :thumbsup:

**Comment by Y-Less** [comment]
Thanks.

I'm giong through both YSI and amx_assembly now, trying to get them both JIT compatible.  Not sure I can get the dynamic_call.inc `SysreqX` functions working as-is (but I'm trying to figure out a suitably ingenious hack, on par with the rest of that library, already got a hack to extract the JIT compiled code's base address - `#emit zero.pri; #emit lctrl 8`).  It may need another JIT modification, I may find a solution, or I may just skip them for now as I don't use them (I know others do, but my primary goal is getting YSI working, but that obviously requires parts of amx_assembly working).

**Pull request merged**
